spring:
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    cache: false
    template-loader-path: classpath:/templates/freemarker/
    suffix: .html
    settings:
      number_format: '0.###'
      default_encoding: 'UTF-8'
    expose-spring-macro-helpers: true
auto_import: spring.ftl as s
